import Head from "next/head";
//import styles from "../styles/Home.module.css";
import { getFacebookPosts } from "./api/queries/getFacebookPosts";

import { GetStaticProps } from "next";
import { Post } from "../interfaces";
import RoomDisplay from "../components/RoomDisplay";

type FacebookProps = {
  posts: Post[];
  preview: boolean;
};

export default function Facebook(props: FacebookProps) {
  return (
    <div className="screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <div id="container">
          <div id="monitor">
            <div id="monitorscreen">
              <RoomDisplay posts={props.posts} />
            </div>
          </div>
        </div>
      </main>

      {/* <footer>
        <Footer />
      </footer> */}
    </div>
  );
}

export const getStaticProps: GetStaticProps = async ({ preview = false }) => {
  const { posts } = await getFacebookPosts(preview);

  return {
    props: {
      posts: posts,
    },
    revalidate: 10,
  };
};
