version: '2.4'

services:
  init:
    healthcheck:
      test: ["CMD", "powershell", "ps"]
    image: ${REGISTRY}demo/${COMPOSE_PROJECT_NAME}-init:${SITECORE_VERSION}-linux-${DEMO_VERSION}
    build:
      context: ./docker/build/init
      dockerfile: Dockerfile.linux
      args:
        BUILD_IMAGE: mcr.microsoft.com/dotnet/sdk:3.1-alpine
        BASE_IMAGE: mcr.microsoft.com/dotnet/runtime:3.1-alpine
    environment:
      ADMIN_PASSWORD: ${SITECORE_ADMIN_PASSWORD}
      ADMIN_USER_NAME: "admin"
      HOST_CM: "http://cm"
      HOST_ID: "http://id"
