import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';

import OrderDetailsContent from '../../components/Account/OrderDetailsContent';
import { OrderWorksheet } from 'ordercloud-javascript-sdk';
import { MockSlice, MockStore } from '../mock-store';
import { loggedInAuthSlice, cartSlice, productCacheSlice } from '../Checkout/CheckoutCommon';

export default {
  title: 'Components/Account/OrderDetailsContent',
  component: OrderDetailsContent,
} as ComponentMeta<typeof OrderDetailsContent>;

const slices: MockSlice[] = [cartSlice, productCacheSlice, loggedInAuthSlice];

const Template: ComponentStory<typeof OrderDetailsContent> = (args) => (
  <MockStore sliceOrSlices={slices}>
    <OrderDetailsContent {...args} />
  </MockStore>
);

const creditCard = {
  CardholderName: 'John Smith',
  PartialAccountNumber: '1111',
  ExpirationDate: '2024-05-01T04:00:00+00:00',
};

const orderOne = {
  Order: {
    ID: 'i2fnCwvqQkyJ9LMrbi_Qcw',
    FromUser: {
      ID: 'ZqCTffhXQ0Of4RiFFpRFqQ',
      Username: 'test451summit',
      Password: null,
      FirstName: 'Test',
      LastName: 'User',
      Email: 'test.user@sitecore.com',
      Phone: null,
      TermsAccepted: null,
      Active: true,
      xp: null,
      AvailableRoles: null,
      Locale: null,
      DateCreated: '2022-04-25T21:07:10.43+00:00',
      PasswordLastSetDate: '2022-04-25T21:07:10.477+00:00',
    },
    FromCompanyID: 'public-storefront',
    ToCompanyID: 'play-summit-ordercloud-discover',
    FromUserID: 'ZqCTffhXQ0Of4RiFFpRFqQ',
    BillingAddressID: null,
    BillingAddress: {
      ID: null,
      DateCreated: null,
      CompanyName: null,
      FirstName: null,
      LastName: null,
      Street1: '6818 Gaines Ferry Road',
      Street2: null,
      City: 'Flowery Branch',
      State: 'GA',
      Zip: '30542',
      Country: 'US',
      Phone: null,
      AddressName: 'Home',
      xp: null,
    },
    ShippingAddressID: null,
    Comments: null,
    LineItemCount: 1,
    Status: 'Open',
    DateCreated: '2022-04-25T21:11:46.563+00:00',
    DateSubmitted: '2022-04-26T15:08:40.013+00:00',
    DateApproved: null,
    DateDeclined: null,
    DateCanceled: null,
    DateCompleted: null,
    LastUpdated: '2022-04-26T15:08:40.06+00:00',
    Subtotal: 15.0,
    ShippingCost: 9.99,
    TaxCost: 1.75,
    PromotionDiscount: 0.0,
    Currency: null,
    Total: 26.74,
    IsSubmitted: true,
    xp: null,
  },
  LineItems: [
    {
      ID: 'zs5tUpQzDUq3jpLyjc7kgg',
      ProductID: 'PSPRFSAW',
      Quantity: 1,
      DateAdded: '2022-04-25T21:11:46.79+00:00',
      QuantityShipped: 0,
      UnitPrice: 15.0,
      PromotionDiscount: 0.0,
      LineTotal: 15.0,
      LineSubtotal: 15.0,
      CostCenter: null,
      DateNeeded: null,
      ShippingAccount: null,
      ShippingAddressID: null,
      ShipFromAddressID: null,
      Product: {
        ID: 'PSPRFSAW',
        Name: 'Strengthening Ab Wheel',
        Description:
          'An ab wheel makes it easy for you to target your arms, back, and core comfortably with a large wheel width for extra stability and beveled edges for smooth directional transitions. The wheel also has a raised, non-slip handle texture that provides you with a superior grip so you can focus on your body and movement. Each ab wheel comes with an exercise guide to help you get started &mdash; or continue on &mdash; your journey to feeling and being your best self.\r\n\r\nWhen families come together to discover the joy of staying active. From running errands to running intervals, the collection AIMs to propel you forward with thoughtfully designed pieces that fit and feel great &mdash; movement is the core of this performance line, with a 100% satisfaction guarantee.',
        Returnable: false,
        QuantityMultiplier: 1,
        ShipWeight: null,
        ShipHeight: null,
        ShipWidth: null,
        ShipLength: null,
        DefaultSupplierID: null,
        xp: {
          Images: [
            {
              Url: 'https://ch.sitecoredemo.com/api/public/content/abb-wheel-1-product?v=9dbb093f',
              ThumbnailUrl: 'undefined',
              Tags: null,
            },
          ],
          ProductUrl: '#',
          Status: 'Draft',
          IsResale: false,
          IntegrationData: null,
          HasVariants: false,
          Note: '',
          Tax: {
            Category: 'P0000000',
            Code: 'PC030156',
            Description:
              'Clothing And Related Products (Business-To-Business)-Work clothes (other)',
          },
          UnitOfMeasure: {
            Qty: 1,
            Unit: 'Per',
          },
          ProductType: 'Standard',
          SizeTier: 'D',
          Accessorials: null,
          Currency: 'USD',
          ArtworkRequired: false,
          PromotionEligible: true,
          FreeShipping: false,
          FreeShippingMessage: 'Free Shipping',
          Documents: null,
        },
      },
      Variant: {
        ID: 'PSPRFSAW-GL',
        Name: null,
        Description: null,
        ShipWeight: null,
        ShipHeight: null,
        ShipWidth: null,
        ShipLength: null,
        xp: null,
      },
      ShippingAddress: {
        ID: null,
        DateCreated: null,
        CompanyName: null,
        FirstName: null,
        LastName: null,
        Street1: '6818 Gaines Ferry Road',
        Street2: null,
        City: 'Flowery Branch',
        State: 'GA',
        Zip: '30542',
        Country: 'US',
        Phone: null,
        AddressName: 'Home',
        xp: null,
      },
      ShipFromAddress: null,
      SupplierID: null,
      InventoryRecordID: null,
      PriceScheduleID: null,
      PriceOverridden: true,
      Specs: [
        {
          SpecID: 'PSPRFSAW-Color',
          Name: 'Color',
          OptionID: 'B-10U4o5I0C36QpO5bhYmA',
          Value: 'Green',
          PriceMarkupType: 'NoMarkup',
          PriceMarkup: null,
        },
        {
          SpecID: 'PSPRFSAW-Size',
          Name: 'Size',
          OptionID: 'juPPqnZ58UmlD5Xf4AYVzA',
          Value: 'Large',
          PriceMarkupType: 'NoMarkup',
          PriceMarkup: null,
        },
        {
          SpecID: 'PSPRFSAW-Name',
          Name: 'Name',
          OptionID: null,
          Value: null,
          PriceMarkupType: null,
          PriceMarkup: null,
        },
      ],
      xp: null,
    },
  ],
  OrderPromotions: [],
  ShipEstimateResponse: {
    ShipEstimates: [
      {
        ID: 'STATIC_SINGLE_SHIPMENT',
        xp: null,
        SelectedShipMethodID: 'STANDARD_DELIVERY',
        ShipEstimateItems: [
          {
            LineItemID: 'zs5tUpQzDUq3jpLyjc7kgg',
            Quantity: 1,
          },
        ],
        ShipMethods: [
          {
            ID: 'STANDARD_DELIVERY',
            Name: 'Standard Delivery',
            Cost: 9.99,
            EstimatedTransitDays: 3,
            xp: {
              Description: 'Receive your order at your home in 3-5 business days',
            },
          },
          {
            ID: 'EXPRESS_DELIVERY',
            Name: 'Express Delivery',
            Cost: 19.99,
            EstimatedTransitDays: 1,
            xp: {
              Description: 'Receive your order at your home in 1-2 business days',
            },
          },
          {
            ID: 'PICKUP_FROM_SUMMIT',
            Name: 'Pick up from the Summit',
            Cost: 0.0,
            EstimatedTransitDays: 0,
            xp: {
              Description: 'Pick up your order at the summit front desk',
            },
          },
          {
            ID: 'PICKUP_IN_STORE',
            Name: 'Pick up in store',
            Cost: 0.0,
            EstimatedTransitDays: 0,
            xp: {
              Description: 'Pick up your order in-store',
            },
          },
        ],
      },
    ],
    HttpStatusCode: 200,
    UnhandledErrorBody: null,
    xp: null,
  },
  OrderCalculateResponse: {
    LineItemOverrides: null,
    ShippingTotal: null,
    TaxTotal: 1.75,
    HttpStatusCode: 200,
    UnhandledErrorBody: null,
    xp: null,
  },
  OrderSubmitResponse: {
    HttpStatusCode: 405,
    UnhandledErrorBody: '',
    xp: null,
  },
  OrderSubmitForApprovalResponse: null,
  OrderApprovedResponse: null,
} as unknown as OrderWorksheet;

const orderTwo = {
  Order: {
    ID: 'oumsvRHDj0KG4sgAsx7xpQ',
    FromUser: {
      ID: 'ZqCTffhXQ0Of4RiFFpRFqQ',
      Username: 'test451summit',
      Password: null,
      FirstName: 'Test',
      LastName: 'User',
      Email: 'test.user@sitecore.com',
      Phone: null,
      TermsAccepted: null,
      Active: true,
      xp: null,
      AvailableRoles: null,
      Locale: null,
      DateCreated: '2022-04-25T21:07:10.43+00:00',
      PasswordLastSetDate: '2022-04-25T21:07:10.477+00:00',
    },
    FromCompanyID: 'public-storefront',
    ToCompanyID: 'play-summit-ordercloud-discover',
    FromUserID: 'ZqCTffhXQ0Of4RiFFpRFqQ',
    BillingAddressID: null,
    BillingAddress: {
      ID: null,
      DateCreated: null,
      CompanyName: null,
      FirstName: null,
      LastName: null,
      Street1: '6818 Gaines Ferry Road',
      Street2: null,
      City: 'Flowery Branch',
      State: 'GA',
      Zip: '30542',
      Country: 'US',
      Phone: null,
      AddressName: 'Home',
      xp: null,
    },
    ShippingAddressID: null,
    Comments: null,
    LineItemCount: 1,
    Status: 'Open',
    DateCreated: '2022-04-26T20:07:24.79+00:00',
    DateSubmitted: '2022-04-26T20:07:57.333+00:00',
    DateApproved: null,
    DateDeclined: null,
    DateCanceled: null,
    DateCompleted: null,
    LastUpdated: '2022-04-26T20:07:57.383+00:00',
    Subtotal: 15.0,
    ShippingCost: 9.99,
    TaxCost: 1.75,
    PromotionDiscount: 0.0,
    Currency: null,
    Total: 26.74,
    IsSubmitted: true,
    xp: null,
  },
  LineItems: [
    {
      ID: 'Cqs8zepCLUGtL9R3KQm83Q',
      ProductID: 'PSPRFSAW',
      Quantity: 1,
      DateAdded: '2022-04-26T20:07:25.06+00:00',
      QuantityShipped: 0,
      UnitPrice: 15.0,
      PromotionDiscount: 0.0,
      LineTotal: 15.0,
      LineSubtotal: 15.0,
      CostCenter: null,
      DateNeeded: null,
      ShippingAccount: null,
      ShippingAddressID: null,
      ShipFromAddressID: null,
      Product: {
        ID: 'PSPRFSAW',
        Name: 'Strengthening Ab Wheel',
        Description:
          'An ab wheel makes it easy for you to target your arms, back, and core comfortably with a large wheel width for extra stability and beveled edges for smooth directional transitions. The wheel also has a raised, non-slip handle texture that provides you with a superior grip so you can focus on your body and movement. Each ab wheel comes with an exercise guide to help you get started &mdash; or continue on &mdash; your journey to feeling and being your best self.\r\n\r\nWhen families come together to discover the joy of staying active. From running errands to running intervals, the collection AIMs to propel you forward with thoughtfully designed pieces that fit and feel great &mdash; movement is the core of this performance line, with a 100% satisfaction guarantee.',
        Returnable: false,
        QuantityMultiplier: 1,
        ShipWeight: null,
        ShipHeight: null,
        ShipWidth: null,
        ShipLength: null,
        DefaultSupplierID: null,
        xp: {
          Images: [
            {
              Url: 'https://ch.sitecoredemo.com/api/public/content/abb-wheel-1-product?v=9dbb093f',
              ThumbnailUrl: 'undefined',
              Tags: null,
            },
          ],
          ProductUrl: '#',
          Status: 'Draft',
          IsResale: false,
          IntegrationData: null,
          HasVariants: false,
          Note: '',
          Tax: {
            Category: 'P0000000',
            Code: 'PC030156',
            Description:
              'Clothing And Related Products (Business-To-Business)-Work clothes (other)',
          },
          UnitOfMeasure: {
            Qty: 1,
            Unit: 'Per',
          },
          ProductType: 'Standard',
          SizeTier: 'D',
          Accessorials: null,
          Currency: 'USD',
          ArtworkRequired: false,
          PromotionEligible: true,
          FreeShipping: false,
          FreeShippingMessage: 'Free Shipping',
          Documents: null,
        },
      },
      Variant: {
        ID: 'PSPRFSAW-BM',
        Name: null,
        Description: null,
        ShipWeight: null,
        ShipHeight: null,
        ShipWidth: null,
        ShipLength: null,
        xp: null,
      },
      ShippingAddress: {
        ID: null,
        DateCreated: null,
        CompanyName: null,
        FirstName: null,
        LastName: null,
        Street1: '6818 Gaines Ferry Road',
        Street2: null,
        City: 'Flowery Branch',
        State: 'GA',
        Zip: '30542',
        Country: 'US',
        Phone: null,
        AddressName: 'Home',
        xp: null,
      },
      ShipFromAddress: null,
      SupplierID: null,
      InventoryRecordID: null,
      PriceScheduleID: null,
      PriceOverridden: true,
      Specs: [
        {
          SpecID: 'PSPRFSAW-Color',
          Name: 'Color',
          OptionID: 'MYw46lDJwEGIFPTcwxVqsQ',
          Value: 'Blue',
          PriceMarkupType: 'NoMarkup',
          PriceMarkup: null,
        },
        {
          SpecID: 'PSPRFSAW-Size',
          Name: 'Size',
          OptionID: 'QLVAT4S67UCD1e_VEINHOQ',
          Value: 'Medium',
          PriceMarkupType: 'NoMarkup',
          PriceMarkup: null,
        },
        {
          SpecID: 'PSPRFSAW-Name',
          Name: 'Name',
          OptionID: null,
          Value: null,
          PriceMarkupType: null,
          PriceMarkup: null,
        },
      ],
      xp: null,
    },
  ],
  OrderPromotions: [],
  ShipEstimateResponse: {
    ShipEstimates: [
      {
        ID: 'STATIC_SINGLE_SHIPMENT',
        xp: null,
        SelectedShipMethodID: 'STANDARD_DELIVERY',
        ShipEstimateItems: [
          {
            LineItemID: 'Cqs8zepCLUGtL9R3KQm83Q',
            Quantity: 1,
          },
        ],
        ShipMethods: [
          {
            ID: 'STANDARD_DELIVERY',
            Name: 'Standard Delivery',
            Cost: 9.99,
            EstimatedTransitDays: 3,
            xp: {
              Description: 'Receive your order at your home in 3-5 business days',
            },
          },
          {
            ID: 'EXPRESS_DELIVERY',
            Name: 'Express Delivery',
            Cost: 19.99,
            EstimatedTransitDays: 1,
            xp: {
              Description: 'Receive your order at your home in 1-2 business days',
            },
          },
          {
            ID: 'PICKUP_FROM_SUMMIT',
            Name: 'Pick up from the Summit',
            Cost: 0.0,
            EstimatedTransitDays: 0,
            xp: {
              Description: 'Pick up your order at the summit front desk',
            },
          },
          {
            ID: 'PICKUP_IN_STORE',
            Name: 'Pick up in store',
            Cost: 0.0,
            EstimatedTransitDays: 0,
            xp: {
              Description: 'Pick up your order in-store',
            },
          },
        ],
      },
    ],
    HttpStatusCode: 200,
    UnhandledErrorBody: null,
    xp: null,
  },
  OrderCalculateResponse: {
    LineItemOverrides: null,
    ShippingTotal: null,
    TaxTotal: 1.75,
    HttpStatusCode: 200,
    UnhandledErrorBody: null,
    xp: null,
  },
  OrderSubmitResponse: {
    HttpStatusCode: 405,
    UnhandledErrorBody: '',
    xp: null,
  },
  OrderSubmitForApprovalResponse: null,
  OrderApprovedResponse: null,
} as unknown as OrderWorksheet;

const orderThree = {
  Order: {
    ID: 'nl3bNB-I_EmL7IhXMH0ctw',
    FromUser: {
      ID: 'ZqCTffhXQ0Of4RiFFpRFqQ',
      Username: 'test451summit',
      Password: null,
      FirstName: 'Test',
      LastName: 'User',
      Email: 'test.user@sitecore.com',
      Phone: null,
      TermsAccepted: null,
      Active: true,
      xp: null,
      AvailableRoles: null,
      Locale: null,
      DateCreated: '2022-04-25T21:07:10.43+00:00',
      PasswordLastSetDate: '2022-04-25T21:07:10.477+00:00',
    },
    FromCompanyID: 'public-storefront',
    ToCompanyID: 'play-summit-ordercloud-discover',
    FromUserID: 'ZqCTffhXQ0Of4RiFFpRFqQ',
    BillingAddressID: null,
    BillingAddress: {
      ID: null,
      DateCreated: null,
      CompanyName: null,
      FirstName: null,
      LastName: null,
      Street1: '6818 Gaines Ferry Road',
      Street2: null,
      City: 'Flowery Branch',
      State: 'GA',
      Zip: '30542',
      Country: 'US',
      Phone: null,
      AddressName: 'Home',
      xp: null,
    },
    ShippingAddressID: null,
    Comments: null,
    LineItemCount: 3,
    Status: 'Open',
    DateCreated: '2022-05-18T18:27:57.723+00:00',
    DateSubmitted: '2022-05-18T18:28:48.423+00:00',
    DateApproved: null,
    DateDeclined: null,
    DateCanceled: null,
    DateCompleted: null,
    LastUpdated: '2022-05-18T18:28:48.527+00:00',
    Subtotal: 48.97,
    ShippingCost: 19.99,
    TaxCost: 4.83,
    PromotionDiscount: 0.0,
    Currency: null,
    Total: 73.79,
    IsSubmitted: true,
    xp: null,
  },
  LineItems: [
    {
      ID: '-16ipfNQP0y2yKLXyHRp8w',
      ProductID: 'PSPCCCCBC',
      Quantity: 1,
      DateAdded: '2022-05-18T18:27:57.977+00:00',
      QuantityShipped: 0,
      UnitPrice: 34.99,
      PromotionDiscount: 0.0,
      LineTotal: 34.99,
      LineSubtotal: 34.99,
      CostCenter: null,
      DateNeeded: null,
      ShippingAccount: null,
      ShippingAddressID: null,
      ShipFromAddressID: null,
      Product: {
        ID: 'PSPCCCCBC',
        Name: 'Carbon Cycling Bottle Cage',
        Description:
          'It securely holds the cycling water bottle thanks to a carbon-fiber contruction. Lightweight (0.9 oz.) and very sturdy. Compatible with bicycles with bottle cage screws. Very sturdy carbon-fiber contruction.',
        Returnable: false,
        QuantityMultiplier: 1,
        ShipWeight: null,
        ShipHeight: null,
        ShipWidth: null,
        ShipLength: null,
        DefaultSupplierID: null,
        xp: {
          Images: [
            {
              Url: 'https://ch.sitecoredemo.com/api/public/content/carbon-cycling-bottle-cage-product?v=312458fb',
              ThumbnailUrl: 'undefined',
              Tags: null,
            },
          ],
          ProductUrl: '#',
          Status: 'Draft',
          IsResale: false,
          IntegrationData: null,
          HasVariants: false,
          Note: '',
          Tax: {
            Category: 'P0000000',
            Code: 'PC030156',
            Description:
              'Clothing And Related Products (Business-To-Business)-Work clothes (other)',
          },
          UnitOfMeasure: {
            Qty: 1,
            Unit: 'Per',
          },
          ProductType: 'Standard',
          SizeTier: 'D',
          Accessorials: null,
          Currency: 'USD',
          ArtworkRequired: false,
          PromotionEligible: true,
          FreeShipping: false,
          FreeShippingMessage: 'Free Shipping',
          Documents: null,
        },
      },
      Variant: null,
      ShippingAddress: {
        ID: null,
        DateCreated: null,
        CompanyName: null,
        FirstName: null,
        LastName: null,
        Street1: '6818 Gaines Ferry Road',
        Street2: null,
        City: 'Flowery Branch',
        State: 'GA',
        Zip: '30542',
        Country: 'US',
        Phone: null,
        AddressName: 'Home',
        xp: null,
      },
      ShipFromAddress: null,
      SupplierID: null,
      InventoryRecordID: null,
      PriceScheduleID: 'PSPCCCCBC',
      PriceOverridden: false,
      Specs: [],
      xp: null,
    },
    {
      ID: 'aY0GnlzME0-O2TXrX16PpA',
      ProductID: 'PSPCCCHVA',
      Quantity: 1,
      DateAdded: '2022-05-18T18:28:07.24+00:00',
      QuantityShipped: 0,
      UnitPrice: 6.99,
      PromotionDiscount: 0.0,
      LineTotal: 6.99,
      LineSubtotal: 6.99,
      CostCenter: null,
      DateNeeded: null,
      ShippingAccount: null,
      ShippingAddressID: null,
      ShipFromAddressID: null,
      Product: {
        ID: 'PSPCCCHVA',
        Name: 'Connection Hose and Valve Adapters',
        Description:
          "The Connection Hose and Valve Adapters kit has all the adapters you need to make your pump work with a wide variety of valves. The kit includes:\r\n- A universal adapter that fits Schrader, Presta, Dunlop, Woods and most other types of valves\r\n- A tough vinyl hose that's long enough for many pumps\r\n- An extension hose for those hard-to-reach valves",
        Returnable: false,
        QuantityMultiplier: 1,
        ShipWeight: null,
        ShipHeight: null,
        ShipWidth: null,
        ShipLength: null,
        DefaultSupplierID: null,
        xp: {
          Images: [
            {
              Url: 'https://ch.sitecoredemo.com/api/public/content/connection-hose-and-valve-adapters-product?v=20d7e176',
              ThumbnailUrl: 'undefined',
              Tags: null,
            },
          ],
          ProductUrl: '#',
          Status: 'Draft',
          IsResale: false,
          IntegrationData: null,
          HasVariants: false,
          Note: '',
          Tax: {
            Category: 'P0000000',
            Code: 'PC030156',
            Description:
              'Clothing And Related Products (Business-To-Business)-Work clothes (other)',
          },
          UnitOfMeasure: {
            Qty: 1,
            Unit: 'Per',
          },
          ProductType: 'Standard',
          SizeTier: 'D',
          Accessorials: null,
          Currency: 'USD',
          ArtworkRequired: false,
          PromotionEligible: true,
          FreeShipping: false,
          FreeShippingMessage: 'Free Shipping',
          Documents: null,
        },
      },
      Variant: null,
      ShippingAddress: {
        ID: null,
        DateCreated: null,
        CompanyName: null,
        FirstName: null,
        LastName: null,
        Street1: '6818 Gaines Ferry Road',
        Street2: null,
        City: 'Flowery Branch',
        State: 'GA',
        Zip: '30542',
        Country: 'US',
        Phone: null,
        AddressName: 'Home',
        xp: null,
      },
      ShipFromAddress: null,
      SupplierID: null,
      InventoryRecordID: null,
      PriceScheduleID: 'PSPCCCHVA',
      PriceOverridden: false,
      Specs: [],
      xp: null,
    },
    {
      ID: 'guB6bDIJyEenAc3fbn2yrw',
      ProductID: 'PSPCCFLEDBBL',
      Quantity: 1,
      DateAdded: '2022-05-18T18:28:15.227+00:00',
      QuantityShipped: 0,
      UnitPrice: 6.99,
      PromotionDiscount: 0.0,
      LineTotal: 6.99,
      LineSubtotal: 6.99,
      CostCenter: null,
      DateNeeded: null,
      ShippingAccount: null,
      ShippingAddressID: null,
      ShipFromAddressID: null,
      Product: {
        ID: 'PSPCCFLEDBBL',
        Name: 'Front LED Battery Bike Light',
        Description:
          'We have designed a battery powered bike light to be seen from the front. It has an elastic fastening system that is easy to use. In continuous mode, it will last 32 hours and in flashing mode it will last 44 hours. 2 CR2032 batteries are included.',
        Returnable: false,
        QuantityMultiplier: 1,
        ShipWeight: null,
        ShipHeight: null,
        ShipWidth: null,
        ShipLength: null,
        DefaultSupplierID: null,
        xp: {
          Images: [
            {
              Url: 'https://ch.sitecoredemo.com/api/public/content/front-led-battery-bike-light-product?v=5f40a0d1',
              ThumbnailUrl: 'undefined',
              Tags: null,
            },
          ],
          ProductUrl: '#',
          Status: 'Draft',
          IsResale: false,
          IntegrationData: null,
          HasVariants: false,
          Note: '',
          Tax: {
            Category: 'P0000000',
            Code: 'PC030156',
            Description:
              'Clothing And Related Products (Business-To-Business)-Work clothes (other)',
          },
          UnitOfMeasure: {
            Qty: 1,
            Unit: 'Per',
          },
          ProductType: 'Standard',
          SizeTier: 'D',
          Accessorials: null,
          Currency: 'USD',
          ArtworkRequired: false,
          PromotionEligible: true,
          FreeShipping: false,
          FreeShippingMessage: 'Free Shipping',
          Documents: null,
        },
      },
      Variant: null,
      ShippingAddress: {
        ID: null,
        DateCreated: null,
        CompanyName: null,
        FirstName: null,
        LastName: null,
        Street1: '6818 Gaines Ferry Road',
        Street2: null,
        City: 'Flowery Branch',
        State: 'GA',
        Zip: '30542',
        Country: 'US',
        Phone: null,
        AddressName: 'Home',
        xp: null,
      },
      ShipFromAddress: null,
      SupplierID: null,
      InventoryRecordID: null,
      PriceScheduleID: 'PSPCCFLEDBBL',
      PriceOverridden: false,
      Specs: [],
      xp: null,
    },
  ],
  OrderPromotions: [],
  ShipEstimateResponse: {
    ShipEstimates: [
      {
        ID: 'STATIC_SINGLE_SHIPMENT',
        xp: null,
        SelectedShipMethodID: 'EXPRESS_DELIVERY',
        ShipEstimateItems: [
          {
            LineItemID: '-16ipfNQP0y2yKLXyHRp8w',
            Quantity: 1,
          },
          {
            LineItemID: 'aY0GnlzME0-O2TXrX16PpA',
            Quantity: 1,
          },
          {
            LineItemID: 'guB6bDIJyEenAc3fbn2yrw',
            Quantity: 1,
          },
        ],
        ShipMethods: [
          {
            ID: 'STANDARD_DELIVERY',
            Name: 'Standard Delivery',
            Cost: 9.99,
            EstimatedTransitDays: 3,
            xp: {
              Description: 'Receive your order at your home in 3-5 business days',
            },
          },
          {
            ID: 'EXPRESS_DELIVERY',
            Name: 'Express Delivery',
            Cost: 19.99,
            EstimatedTransitDays: 1,
            xp: {
              Description: 'Receive your order at your home in 1-2 business days',
            },
          },
          {
            ID: 'PICKUP_FROM_SUMMIT',
            Name: 'Pick up from the Summit',
            Cost: 0.0,
            EstimatedTransitDays: 0,
            xp: {
              Description: 'Pick up your order at the summit front desk',
            },
          },
          {
            ID: 'PICKUP_IN_STORE',
            Name: 'Pick up in store',
            Cost: 0.0,
            EstimatedTransitDays: 0,
            xp: {
              Description: 'Pick up your order in-store',
            },
          },
        ],
      },
    ],
    HttpStatusCode: 200,
    UnhandledErrorBody: null,
    xp: null,
  },
  OrderCalculateResponse: {
    LineItemOverrides: null,
    ShippingTotal: null,
    TaxTotal: 4.83,
    HttpStatusCode: 200,
    UnhandledErrorBody: null,
    xp: null,
  },
  OrderSubmitResponse: {
    HttpStatusCode: 405,
    UnhandledErrorBody: '',
    xp: null,
  },
  OrderSubmitForApprovalResponse: null,
  OrderApprovedResponse: null,
} as unknown as OrderWorksheet;

const orderFour = {
  Order: {
    ID: 'iysMV8Oh_UqG3CQfGF49Ow',
    FromUser: {
      ID: 'ZqCTffhXQ0Of4RiFFpRFqQ',
      Username: 'test451summit',
      Password: null,
      FirstName: 'Test',
      LastName: 'User',
      Email: 'test.user@sitecore.com',
      Phone: null,
      TermsAccepted: null,
      Active: true,
      xp: null,
      AvailableRoles: null,
      Locale: null,
      DateCreated: '2022-04-25T21:07:10.43+00:00',
      PasswordLastSetDate: '2022-04-25T21:07:10.477+00:00',
    },
    FromCompanyID: 'public-storefront',
    ToCompanyID: 'play-summit-ordercloud-discover',
    FromUserID: 'ZqCTffhXQ0Of4RiFFpRFqQ',
    BillingAddressID: null,
    BillingAddress: {
      ID: null,
      DateCreated: null,
      CompanyName: null,
      FirstName: null,
      LastName: null,
      Street1: '6818 Gaines Ferry Road',
      Street2: null,
      City: 'Flowery Branch',
      State: 'GA',
      Zip: '30542',
      Country: 'US',
      Phone: null,
      AddressName: 'Home',
      xp: null,
    },
    ShippingAddressID: null,
    Comments: null,
    LineItemCount: 3,
    Status: 'Open',
    DateCreated: '2022-05-18T18:32:07.067+00:00',
    DateSubmitted: '2022-05-18T18:33:02.853+00:00',
    DateApproved: null,
    DateDeclined: null,
    DateCanceled: null,
    DateCompleted: null,
    LastUpdated: '2022-05-18T18:33:02.98+00:00',
    Subtotal: 2315.95,
    ShippingCost: 19.99,
    TaxCost: 163.52,
    PromotionDiscount: 0.0,
    Currency: null,
    Total: 2499.46,
    IsSubmitted: true,
    xp: null,
  },
  LineItems: [
    {
      ID: 'CPFStncBDE24KhjWDMkKxQ',
      ProductID: 'PSPOUSC',
      Quantity: 1,
      DateAdded: '2022-05-18T18:32:07.92+00:00',
      QuantityShipped: 0,
      UnitPrice: 2200.0,
      PromotionDiscount: 0.0,
      LineTotal: 2200.0,
      LineSubtotal: 2200.0,
      CostCenter: null,
      DateNeeded: null,
      ShippingAccount: null,
      ShippingAddressID: null,
      ShipFromAddressID: null,
      Product: {
        ID: 'PSPOUSC',
        Name: 'Studio Cycle',
        Description:
          'If you love a real studio ride, the new ICR50 makes it easy to take on a virtually limitless variety of cycling workouts in the comfort of your own home. Advanced ergonomics and precision design deliver performance every bit as intense as your favorite class.\r\n\r\nBluetooth connects with leading training apps\r\nPrecision resistance lever quickly changes intensity\r\nProtected, rear-mounted flywheel shields critical components',
        Returnable: false,
        QuantityMultiplier: 1,
        ShipWeight: null,
        ShipHeight: null,
        ShipWidth: null,
        ShipLength: null,
        DefaultSupplierID: null,
        xp: {
          Images: [
            {
              Url: 'https://ch.sitecoredemo.com/api/public/content/studio-cycle-product?v=a92478f6',
              ThumbnailUrl: 'undefined',
              Tags: null,
            },
          ],
          ProductUrl: '#',
          Status: 'Draft',
          IsResale: false,
          IntegrationData: null,
          HasVariants: false,
          Note: '',
          Tax: {
            Category: 'P0000000',
            Code: 'PC030156',
            Description:
              'Clothing And Related Products (Business-To-Business)-Work clothes (other)',
          },
          UnitOfMeasure: {
            Qty: 1,
            Unit: 'Per',
          },
          ProductType: 'Standard',
          SizeTier: 'D',
          Accessorials: null,
          Currency: 'USD',
          ArtworkRequired: false,
          PromotionEligible: true,
          FreeShipping: false,
          FreeShippingMessage: 'Free Shipping',
          Documents: null,
        },
      },
      Variant: null,
      ShippingAddress: {
        ID: null,
        DateCreated: null,
        CompanyName: null,
        FirstName: null,
        LastName: null,
        Street1: '6818 Gaines Ferry Road',
        Street2: null,
        City: 'Flowery Branch',
        State: 'GA',
        Zip: '30542',
        Country: 'US',
        Phone: null,
        AddressName: 'Home',
        xp: null,
      },
      ShipFromAddress: null,
      SupplierID: null,
      InventoryRecordID: null,
      PriceScheduleID: 'PSPOUSC',
      PriceOverridden: false,
      Specs: [],
      xp: null,
    },
    {
      ID: 'ugv6MZOIaEONNpxcHuO2eQ',
      ProductID: 'PSPSBC',
      Quantity: 1,
      DateAdded: '2022-05-18T18:32:21.637+00:00',
      QuantityShipped: 0,
      UnitPrice: 15.95,
      PromotionDiscount: 0.0,
      LineTotal: 15.95,
      LineSubtotal: 15.95,
      CostCenter: null,
      DateNeeded: null,
      ShippingAccount: null,
      ShippingAddressID: null,
      ShipFromAddressID: null,
      Product: {
        ID: 'PSPSBC',
        Name: 'Bike Cover',
        Description:
          'The Striva Bike cover is the ultimate protection for your bicycle against all the elements.\r\n\r\nWhether you store your bicycle inside a garage or in the yard, you want it to stay dry, without dust or scratches and protected against sunlight - that&#39;s what this high-quality 190T Nylon waterproof cover will do for you.<br />\r\n\r\n-190T Nylon with PU coating, extremely durable\r\n-Security eyelets at the front, enabling the cover to be locked securely through the bikes front wheel, deterring theft (lock not included).\r\n-Storm strap at the middle, which keeps the cover in place on windy days.\r\n-Elastic hems at the front middle and rear to allow for a nice snug fit under both wheels.\r\n-High-quality drawstring pouch for easy and convenient storage.\r\n-Reflective loops to allow for easy location at night.\r\n\r\nDimensions\r\nNon-stretched size : L 200cm H 100cm W 80cmNote: Please measure your bike prior to purchase to ensure your cover fits',
        Returnable: false,
        QuantityMultiplier: 1,
        ShipWeight: null,
        ShipHeight: null,
        ShipWidth: null,
        ShipLength: null,
        DefaultSupplierID: null,
        xp: {
          Images: [
            {
              Url: 'https://ch.sitecoredemo.com/api/public/content/bike-cover-product?v=1a005210',
              ThumbnailUrl: 'undefined',
              Tags: null,
            },
          ],
          ProductUrl: '#',
          Status: 'Draft',
          IsResale: false,
          IntegrationData: null,
          HasVariants: false,
          Note: '',
          Tax: {
            Category: 'P0000000',
            Code: 'PC030156',
            Description:
              'Clothing And Related Products (Business-To-Business)-Work clothes (other)',
          },
          UnitOfMeasure: {
            Qty: 1,
            Unit: 'Per',
          },
          ProductType: 'Standard',
          SizeTier: 'D',
          Accessorials: null,
          Currency: 'USD',
          ArtworkRequired: false,
          PromotionEligible: true,
          FreeShipping: false,
          FreeShippingMessage: 'Free Shipping',
          Documents: null,
        },
      },
      Variant: null,
      ShippingAddress: {
        ID: null,
        DateCreated: null,
        CompanyName: null,
        FirstName: null,
        LastName: null,
        Street1: '6818 Gaines Ferry Road',
        Street2: null,
        City: 'Flowery Branch',
        State: 'GA',
        Zip: '30542',
        Country: 'US',
        Phone: null,
        AddressName: 'Home',
        xp: null,
      },
      ShipFromAddress: null,
      SupplierID: null,
      InventoryRecordID: null,
      PriceScheduleID: 'PSPSBC',
      PriceOverridden: false,
      Specs: [],
      xp: null,
    },
    {
      ID: 'TjV_TBp7Pka-6FYuM-WUaw',
      ProductID: 'PSPOUS',
      Quantity: 1,
      DateAdded: '2022-05-18T18:32:40.443+00:00',
      QuantityShipped: 0,
      UnitPrice: 100.0,
      PromotionDiscount: 0.0,
      LineTotal: 100.0,
      LineSubtotal: 100.0,
      CostCenter: null,
      DateNeeded: null,
      ShippingAccount: null,
      ShippingAddressID: null,
      ShipFromAddressID: null,
      Product: {
        ID: 'PSPOUS',
        Name: 'Smartwatch',
        Description:
          'Tough and durable\r\nTested to the extreme, waterproof 100 m. The highest grade of materials: sapphire glass and grade 5 titanium in selected models.\r\n\r\nBuilt to last\r\nBattery life 25 hours with best GPS, up to 170 hours in Tour mode.\r\n\r\nPassionate about sports\r\nSport expertise and support for over 80 sports (running, cycling, swimming, hiking, and many more).\r\n\r\nDesigned for adventure\r\nBarometric altitude, route navigation on the watch, and sport-specific heatmaps on OverUnder app.',
        Returnable: false,
        QuantityMultiplier: 1,
        ShipWeight: null,
        ShipHeight: null,
        ShipWidth: null,
        ShipLength: null,
        DefaultSupplierID: null,
        xp: {
          Images: [
            {
              Url: 'https://ch.sitecoredemo.com/api/public/content/smartwatch-product?v=11095651',
              ThumbnailUrl: 'undefined',
              Tags: null,
            },
          ],
          ProductUrl: '#',
          Status: 'Draft',
          IsResale: false,
          IntegrationData: null,
          HasVariants: false,
          Note: '',
          Tax: {
            Category: 'P0000000',
            Code: 'PC030156',
            Description:
              'Clothing And Related Products (Business-To-Business)-Work clothes (other)',
          },
          UnitOfMeasure: {
            Qty: 1,
            Unit: 'Per',
          },
          ProductType: 'Standard',
          SizeTier: 'D',
          Accessorials: null,
          Currency: 'USD',
          ArtworkRequired: false,
          PromotionEligible: true,
          FreeShipping: false,
          FreeShippingMessage: 'Free Shipping',
          Documents: null,
        },
      },
      Variant: null,
      ShippingAddress: {
        ID: null,
        DateCreated: null,
        CompanyName: null,
        FirstName: null,
        LastName: null,
        Street1: '6818 Gaines Ferry Road',
        Street2: null,
        City: 'Flowery Branch',
        State: 'GA',
        Zip: '30542',
        Country: 'US',
        Phone: null,
        AddressName: 'Home',
        xp: null,
      },
      ShipFromAddress: null,
      SupplierID: null,
      InventoryRecordID: null,
      PriceScheduleID: 'PSPOUS',
      PriceOverridden: false,
      Specs: [],
      xp: null,
    },
  ],
  OrderPromotions: [],
  ShipEstimateResponse: {
    ShipEstimates: [
      {
        ID: 'STATIC_SINGLE_SHIPMENT',
        xp: null,
        SelectedShipMethodID: 'EXPRESS_DELIVERY',
        ShipEstimateItems: [
          {
            LineItemID: 'CPFStncBDE24KhjWDMkKxQ',
            Quantity: 1,
          },
          {
            LineItemID: 'ugv6MZOIaEONNpxcHuO2eQ',
            Quantity: 1,
          },
          {
            LineItemID: 'TjV_TBp7Pka-6FYuM-WUaw',
            Quantity: 1,
          },
        ],
        ShipMethods: [
          {
            ID: 'STANDARD_DELIVERY',
            Name: 'Standard Delivery',
            Cost: 9.99,
            EstimatedTransitDays: 3,
            xp: {
              Description: 'Receive your order at your home in 3-5 business days',
            },
          },
          {
            ID: 'EXPRESS_DELIVERY',
            Name: 'Express Delivery',
            Cost: 19.99,
            EstimatedTransitDays: 1,
            xp: {
              Description: 'Receive your order at your home in 1-2 business days',
            },
          },
          {
            ID: 'PICKUP_FROM_SUMMIT',
            Name: 'Pick up from the Summit',
            Cost: 0.0,
            EstimatedTransitDays: 0,
            xp: {
              Description: 'Pick up your order at the summit front desk',
            },
          },
          {
            ID: 'PICKUP_IN_STORE',
            Name: 'Pick up in store',
            Cost: 0.0,
            EstimatedTransitDays: 0,
            xp: {
              Description: 'Pick up your order in-store',
            },
          },
        ],
      },
    ],
    HttpStatusCode: 200,
    UnhandledErrorBody: null,
    xp: null,
  },
  OrderCalculateResponse: {
    LineItemOverrides: null,
    ShippingTotal: null,
    TaxTotal: 163.52,
    HttpStatusCode: 200,
    UnhandledErrorBody: null,
    xp: null,
  },
  OrderSubmitResponse: {
    HttpStatusCode: 405,
    UnhandledErrorBody: '',
    xp: null,
  },
  OrderSubmitForApprovalResponse: null,
  OrderApprovedResponse: null,
} as unknown as OrderWorksheet;

export const OrderOne = Template.bind({});
OrderOne.args = {
  order: orderOne,
  creditCard,
  shipMethod: orderOne.ShipEstimateResponse.ShipEstimates[0].ShipMethods[0],
};

export const OrderTwo = Template.bind({});
OrderTwo.args = {
  order: orderTwo,
  creditCard,
  shipMethod: orderTwo.ShipEstimateResponse.ShipEstimates[0].ShipMethods[0],
};

export const OrderThree = Template.bind({});
OrderThree.args = {
  order: orderThree,
  creditCard,
  shipMethod: orderThree.ShipEstimateResponse.ShipEstimates[0].ShipMethods[1],
};

export const OrderFour = Template.bind({});
OrderFour.args = {
  order: orderFour,
  creditCard,
  shipMethod: orderFour.ShipEstimateResponse.ShipEstimates[0].ShipMethods[1],
};

export const NoOrder = Template.bind({});
NoOrder.args = {};
