import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';

import OrderHistoryContent from '../../components/Account/OrderHistoryContent';
import { Order } from 'ordercloud-javascript-sdk';

export default {
  title: 'Components/Account/OrderHistoryContent',
  component: OrderHistoryContent,
} as ComponentMeta<typeof OrderHistoryContent>;

const Template: ComponentStory<typeof OrderHistoryContent> = (args) => (
  <OrderHistoryContent {...args} />
);

const orders = [
  {
    ID: 'iysMV8Oh_UqG3CQfGF49Ow',
    FromUser: {
      ID: 'ZqCTffhXQ0Of4RiFFpRFqQ',
      Username: 'test451summit',
      Password: null,
      FirstName: 'Test',
      LastName: 'User',
      Email: 'test.user@sitecore.com',
      Phone: null,
      TermsAccepted: null,
      Active: true,
      xp: null,
      AvailableRoles: null,
      Locale: null,
      DateCreated: '2022-04-25T21:07:10.43+00:00',
      PasswordLastSetDate: '2022-04-25T21:07:10.477+00:00',
    },
    FromCompanyID: 'public-storefront',
    ToCompanyID: 'play-summit-ordercloud-discover',
    FromUserID: 'ZqCTffhXQ0Of4RiFFpRFqQ',
    BillingAddressID: null,
    BillingAddress: {
      ID: null,
      DateCreated: null,
      CompanyName: null,
      FirstName: null,
      LastName: null,
      Street1: '6818 Gaines Ferry Road',
      Street2: null,
      City: 'Flowery Branch',
      State: 'GA',
      Zip: '30542',
      Country: 'US',
      Phone: null,
      AddressName: 'Home',
      xp: null,
    },
    ShippingAddressID: null,
    Comments: null,
    LineItemCount: 3,
    Status: 'Open',
    DateCreated: '2022-05-18T18:32:07.067+00:00',
    DateSubmitted: '2022-05-18T18:33:02.853+00:00',
    DateApproved: null,
    DateDeclined: null,
    DateCanceled: null,
    DateCompleted: null,
    LastUpdated: '2022-05-18T18:33:02.98+00:00',
    Subtotal: 2315.95,
    ShippingCost: 19.99,
    TaxCost: 163.52,
    PromotionDiscount: 0.0,
    Currency: null,
    Total: 2499.46,
    IsSubmitted: true,
    xp: null,
  },
  {
    ID: 'nl3bNB-I_EmL7IhXMH0ctw',
    FromUser: {
      ID: 'ZqCTffhXQ0Of4RiFFpRFqQ',
      Username: 'test451summit',
      Password: null,
      FirstName: 'Test',
      LastName: 'User',
      Email: 'test.user@sitecore.com',
      Phone: null,
      TermsAccepted: null,
      Active: true,
      xp: null,
      AvailableRoles: null,
      Locale: null,
      DateCreated: '2022-04-25T21:07:10.43+00:00',
      PasswordLastSetDate: '2022-04-25T21:07:10.477+00:00',
    },
    FromCompanyID: 'public-storefront',
    ToCompanyID: 'play-summit-ordercloud-discover',
    FromUserID: 'ZqCTffhXQ0Of4RiFFpRFqQ',
    BillingAddressID: null,
    BillingAddress: {
      ID: null,
      DateCreated: null,
      CompanyName: null,
      FirstName: null,
      LastName: null,
      Street1: '6818 Gaines Ferry Road',
      Street2: null,
      City: 'Flowery Branch',
      State: 'GA',
      Zip: '30542',
      Country: 'US',
      Phone: null,
      AddressName: 'Home',
      xp: null,
    },
    ShippingAddressID: null,
    Comments: null,
    LineItemCount: 3,
    Status: 'Open',
    DateCreated: '2022-05-18T18:27:57.723+00:00',
    DateSubmitted: '2022-05-18T18:28:48.423+00:00',
    DateApproved: null,
    DateDeclined: null,
    DateCanceled: null,
    DateCompleted: null,
    LastUpdated: '2022-05-18T18:28:48.527+00:00',
    Subtotal: 48.97,
    ShippingCost: 19.99,
    TaxCost: 4.83,
    PromotionDiscount: 0.0,
    Currency: null,
    Total: 73.79,
    IsSubmitted: true,
    xp: null,
  },
  {
    ID: 'oumsvRHDj0KG4sgAsx7xpQ',
    FromUser: {
      ID: 'ZqCTffhXQ0Of4RiFFpRFqQ',
      Username: 'test451summit',
      Password: null,
      FirstName: 'Test',
      LastName: 'User',
      Email: 'test.user@sitecore.com',
      Phone: null,
      TermsAccepted: null,
      Active: true,
      xp: null,
      AvailableRoles: null,
      Locale: null,
      DateCreated: '2022-04-25T21:07:10.43+00:00',
      PasswordLastSetDate: '2022-04-25T21:07:10.477+00:00',
    },
    FromCompanyID: 'public-storefront',
    ToCompanyID: 'play-summit-ordercloud-discover',
    FromUserID: 'ZqCTffhXQ0Of4RiFFpRFqQ',
    BillingAddressID: null,
    BillingAddress: {
      ID: null,
      DateCreated: null,
      CompanyName: null,
      FirstName: null,
      LastName: null,
      Street1: '6818 Gaines Ferry Road',
      Street2: null,
      City: 'Flowery Branch',
      State: 'GA',
      Zip: '30542',
      Country: 'US',
      Phone: null,
      AddressName: 'Home',
      xp: null,
    },
    ShippingAddressID: null,
    Comments: null,
    LineItemCount: 1,
    Status: 'Open',
    DateCreated: '2022-04-26T20:07:24.79+00:00',
    DateSubmitted: '2022-04-26T20:07:57.333+00:00',
    DateApproved: null,
    DateDeclined: null,
    DateCanceled: null,
    DateCompleted: null,
    LastUpdated: '2022-04-26T20:07:57.383+00:00',
    Subtotal: 15.0,
    ShippingCost: 9.99,
    TaxCost: 1.75,
    PromotionDiscount: 0.0,
    Currency: null,
    Total: 26.74,
    IsSubmitted: true,
    xp: null,
  },
  {
    ID: 'i2fnCwvqQkyJ9LMrbi_Qcw',
    FromUser: {
      ID: 'ZqCTffhXQ0Of4RiFFpRFqQ',
      Username: 'test451summit',
      Password: null,
      FirstName: 'Test',
      LastName: 'User',
      Email: 'test.user@sitecore.com',
      Phone: null,
      TermsAccepted: null,
      Active: true,
      xp: null,
      AvailableRoles: null,
      Locale: null,
      DateCreated: '2022-04-25T21:07:10.43+00:00',
      PasswordLastSetDate: '2022-04-25T21:07:10.477+00:00',
    },
    FromCompanyID: 'public-storefront',
    ToCompanyID: 'play-summit-ordercloud-discover',
    FromUserID: 'ZqCTffhXQ0Of4RiFFpRFqQ',
    BillingAddressID: null,
    BillingAddress: {
      ID: null,
      DateCreated: null,
      CompanyName: null,
      FirstName: null,
      LastName: null,
      Street1: '6818 Gaines Ferry Road',
      Street2: null,
      City: 'Flowery Branch',
      State: 'GA',
      Zip: '30542',
      Country: 'US',
      Phone: null,
      AddressName: 'Home',
      xp: null,
    },
    ShippingAddressID: null,
    Comments: null,
    LineItemCount: 1,
    Status: 'Open',
    DateCreated: '2022-04-25T21:11:46.563+00:00',
    DateSubmitted: '2022-04-26T15:08:40.013+00:00',
    DateApproved: null,
    DateDeclined: null,
    DateCanceled: null,
    DateCompleted: null,
    LastUpdated: '2022-04-26T15:08:40.06+00:00',
    Subtotal: 15.0,
    ShippingCost: 9.99,
    TaxCost: 1.75,
    PromotionDiscount: 0.0,
    Currency: null,
    Total: 26.74,
    IsSubmitted: true,
    xp: null,
  },
] as Order[];

export const Default = Template.bind({});
Default.args = {
  orders,
};

export const NoOrders = Template.bind({});
NoOrders.args = {};

export const EmptyOrders = Template.bind({});
EmptyOrders.args = {
  orders: [],
};
