---
ID: "9e25e09b-971e-409e-aa42-8d54ba7cc570"
Parent: "68dc89a4-1b04-59a8-9c4e-3b49d6c61052"
Template: "d8aa73e1-c275-4eee-bb9d-333925e51952"
Path: "/sitecore/content/EdgeWebsite/home/sessions/Train smarter not harder"
SharedFields:
- ID: "9b0343a9-9f69-4e0f-a059-9215bc8fe422"
  Hint: EntityIdentifier
  Value: HOl1YUjfoEScb2gWsvJGZA
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: "Train smarter not harder"
  Versions:
  - Version: 1
    Fields:
    - ID: "025df6a5-2001-449f-8f76-02be5353905c"
      Hint: Audience
      Value: "{4D758CED-1AD4-46C7-8E72-B42BE54A08E8}"
    - ID: "21df785e-14dd-4c8d-abff-5ae00b693e5e"
      Hint: Description
      Value: |
        <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque volutpat mattis eros. Nullam malesuada erat ut turpis. Suspendisse urna nibh, viverra non, semper suscipit, posuere a, pede.Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque volutpat mattis eros. Nullam malesuada erat ut turpis. Suspendisse urna nibh, viverra non, semper suscipit, posuere a, pede.</p>
                        
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220114T224719Z
    - ID: "3647d085-16e3-44ee-a3f7-c613d0fe17ce"
      Hint: Speakers
      Value: "{BB90AE1B-06D6-480D-A238-F2998721A00D}"
    - ID: "4b2d1962-60eb-4cd1-b8e9-a2c2762ec04c"
      Hint: Image
      Value: |
        <image stylelabs-content-id="38039" thumbnailsrc="https://playsummit.sitecoresandbox.cloud/api/gateway/38039/thumbnail" src="https://playsummit.sitecoresandbox.cloud/api/public/content/a218d495616043568a73c79f05143a93?v=cf7bb555" mediaid="" stylelabs-content-type="Image" alt="Fitness tracker 2" height="4912" width="7360" />
    - ID: "51084853-806c-4e3d-90a3-0eaec3faa3ac"
      Hint: Day
      Value: "{F7B3C20A-6F02-40E3-A4F9-901E1BF420F8}"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        default\Anonymous
    - ID: "5c88d198-7603-4a45-b9f6-682b908c60b9"
      Hint: Timeslots
      Value: "{9FA93929-60C9-47DF-9E5A-C170E6EE2440}"
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        default\Anonymous
    - ID: "6f888071-3e3a-4888-ae95-d90b7df06870"
      Hint: Type
      Value: Session
    - ID: "8058e5a0-d20d-4923-b87d-f56b19efc20f"
      Hint: Name
      Value: "Train smarter not harder"
    - ID: "8c3dff8b-74bc-4a65-af6d-81452a3d9a11"
      Hint: Rooms
      Value: "{80268225-1D8E-477C-A866-0EA047A7876A}"
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "617cac7d-ef29-4a89-a1bf-d0f2bbe0b27f"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        default\Anonymous
    - ID: "cb19a833-48b8-4ad4-a841-09769bbef5c6"
      Hint: Sponsors
      Value: "{C5CEF7C2-8DC6-4B8A-9AD4-D04DEB7B5DAB}"
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220114T230222Z
    - ID: "ed69eacf-5eb2-5050-9d5b-997812318dde"
      Hint: pageTitle
      Value: "Train smarter not harder"
