---
ID: "e29ead4c-b412-4f77-a0f6-1e093b8f30fb"
Parent: "11121733-3469-44c2-9ed3-27c7ea32ec05"
Template: "11121733-3469-44c2-9ed3-27c7ea32ec05"
Path: "/sitecore/templates/Project/Content Hub Entity Types/play-venue-page/__Standard Values"
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{2C211D0C-8DAE-587E-ACCD-DA500C88C3AF}">
        <p
          uid="{EEF24166-4D0F-54C4-8D2C-9CD69F811527}"
          key="hf-nav"
          md="{01038B98-8BBA-5008-AEFE-5E6E9AB8AAB2}" />
        <p
          uid="{B7B75125-02C9-5AC2-B119-1C27802A0788}"
          key="hf-body"
          md="{27E71AA5-BB6A-58D8-AAE2-914BE0CDE164}" />
        <p
          uid="{A6FC32B3-6FC1-5193-A8BD-B7861D63653A}"
          key="hf-personalization-wizard"
          md="{7A650CC4-E487-59AC-BA55-AECD5F63BCF3}" />
        <p
          uid="{11AB78B8-AF0C-5A37-BB7D-2A9676DAE1ED}"
          key="hf-registration-wizard"
          md="{B68F6852-A415-59D2-9009-69CF1ED0972B}" />
        <p
          uid="{79AD51E3-16A8-58E0-8876-7573B90332E8}"
          key="hf-createaccount-form"
          md="{F68972B1-1308-5D11-8316-1AFEECB1BF25}" />
        <p
          uid="{BD1E7498-7C10-55AD-AECC-7675ED701A82}"
          key="hf-createaccount-form-group"
          md="{1B45C243-9663-5D83-9129-A40725AD8785}" />
        <r
          uid="{E439C8F8-7617-5F91-8F7F-C46D6BF3B192}"
          rname="EventDetailsNavigation"
          id="{C42C4419-0E19-5DEB-A3D8-BD5CE1F84B03}"
          par=""
          ph="/hf-nav" />
        <r
          uid="{26C520F9-E8C9-57C3-92BF-012E9AA56078}"
          rname="EventDetailAnonymous"
          ds="{EC3095BB-03BB-5D57-B8FD-1E6D815AB30D}"
          id="{0EFCB51C-7B5E-5FAC-A8B2-79EB2F8ECBDA}"
          par=""
          ph="/hf-body" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181027T230927Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a0ad4381-f8a2-4c66-a547-2e13d4d55e19"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210616T123154Z
    - ID: "fc3b2a6c-042b-421c-9c3d-88c83186ceb9"
      Hint: name
      Value: $name
