---
ID: "e14f6092-e80e-44b1-b257-7aa416243db4"
Parent: "44262889-315a-4f8d-8fb5-243d793fd54a"
Template: "44262889-315a-4f8d-8fb5-243d793fd54a"
Path: /sitecore/templates/Project/edgewebsite/CMP Entities/Advertisement/__Standard Values
SharedFields:
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: 
- ID: "c9283d9e-7c29-4419-9c28-5a5c8ff53e84"
  Hint: __Bucketable
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190614T161122Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{C55B483C-EA7F-4E76-A066-985F7D9396CA}"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d0d06af9-f08e-4d29-948a-282091eafe96"
    - ID: "957519d5-5c6b-40c0-b462-b1dac8f12a03"
      Hint: Eyebrow Title
      Value: $name
    - ID: "b536aa73-95d3-4472-95ec-cc02dfdc0633"
      Hint: ImageTransformation
      Value: banner
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\superuser
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20211116T174808Z
    - ID: "e2d35418-b6ed-4838-90cb-26f98c1d7586"
      Hint: Title
      Value: $name
