---
ID: "f5809647-ccca-420a-8b49-f30184476231"
Parent: "6ce6f007-24f7-43aa-9732-dde2c19de464"
Template: "d8aa73e1-c275-4eee-bb9d-333925e51952"
Path: /sitecore/content/CMP/Sessions/Train smarter
SharedFields:
- ID: "9b0343a9-9f69-4e0f-a059-9215bc8fe422"
  Hint: EntityIdentifier
  Value: CrT3zRfQ80uyiNG6kpazgw
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "088d16c1-3209-4fa9-a133-3776bfdffa32"
      Hint: Duration
      Value: 30 min
    - ID: "21df785e-14dd-4c8d-abff-5ae00b693e5e"
      Hint: Description
      Value: |
        <p>TRAIN SMARTER, NOT HARDER always</p>
        
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210729T194040Z
    - ID: "4b2d1962-60eb-4cd1-b8e9-a2c2762ec04c"
      Hint: Image
      Value: |
        <image stylelabs-content-id="35977" thumbnailsrc="https://mint.stylelabs.io/api/gateway/35977/thumbnail" src="https://mint.stylelabs.io/api/public/content/c65200dcdd944b67b75797fa2b9b9953?v=3280464e" mediaid="" stylelabs-content-type="Image" alt="session-1.jpg" height="400" width="600" />
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        default\Anonymous
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        default\Anonymous
    - ID: "6e6cbcbf-1059-48df-88c8-3f29e5127e5b"
      Hint: Date
      Value: 20210730T183300Z
    - ID: "8058e5a0-d20d-4923-b87d-f56b19efc20f"
      Hint: Name
      Value: Train smarter, not harder
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "8d6224e3-41de-4cfe-9229-fb5b1912d856"
    - ID: "91446149-9f4d-47f2-9fe4-7434ef130c43"
      Hint: Speakers
      Value: "{61AC52CB-DC91-4791-A1AE-71D9CF675083}"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\superuser
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210730T183352Z
