---
ID: "a9092d4a-2e53-54f2-9df8-a660ca6dd434"
Parent: "9141d69c-d7ca-5b8c-baf0-2a9b97681e62"
Template: "9141d69c-d7ca-5b8c-baf0-2a9b97681e62"
Path: /sitecore/templates/Project/edgewebsite/SpeakersGrid/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210615T142046Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b80791af-490a-4da6-b969-40c5623d5248"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210615T142046Z
