---
ID: "2a751a2c-7bb5-50be-b75e-3e4d517d7393"
Parent: "bb2d1f8a-7c29-5ab6-8955-48514a7ef85a"
Template: "bb2d1f8a-7c29-5ab6-8955-48514a7ef85a"
Path: /sitecore/templates/Project/edgewebsite/ContentList/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210706T211742Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "139f4285-0c98-493e-ad74-2cdb08f1357e"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210706T211742Z
