---
ID: "dc6543fb-f949-5e5b-b461-2c7ffb16e67b"
Parent: "7ff7c2d7-f5e1-57f1-a3f3-812418ac08aa"
Template: "7ff7c2d7-f5e1-57f1-a3f3-812418ac08aa"
Path: /sitecore/templates/Project/edgewebsite/ThreeColumnCta/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210726T155123Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "483a7f0b-0cbf-4ca7-816a-f6add0b987f9"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210726T155123Z
