---
ID: "dc6543fb-f949-5e5b-b461-2c7ffb16e67b"
Parent: "7ff7c2d7-f5e1-57f1-a3f3-812418ac08aa"
Template: "7ff7c2d7-f5e1-57f1-a3f3-812418ac08aa"
Path: /sitecore/templates/Project/edgewebsite/ThreeColumnCta/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
