import Head from 'next/head';
import Image from 'next/image';
import banner1 from '../public/banner1.png';
import banner2 from '../public/banner2.png';
import 'react-responsive-carousel/lib/styles/carousel.min.css'; // requires a loader
import { Carousel } from 'react-responsive-carousel';
import Footer from '../components/Footer';

export default function Home() {
  return (
    <div className="screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <div id="container">
          <div id="monitor">
            <div id="monitorscreen">
              <Carousel autoPlay={true} showThumbs={false}>
                <div>
                  <Image src={banner1} alt="Sample" />
                </div>
                <div>
                  <Image src={banner2} alt="Sample" />
                </div>
              </Carousel>
            </div>
          </div>
        </div>
      </main>

      <footer>
        <Footer />
      </footer>
    </div>
  );
}
