import Head from 'next/head';
import { getSessions } from '../api/queries/getSessions';
import { GetStaticProps } from 'next';
import { Session } from '../interfaces';
import RoomDisplay from '../components/RoomDisplay';
import Footer from '../components/Footer';

type RoomProps = {
  sessions: Session[];
  preview: boolean;
};

export default function Room(props: RoomProps) {
  return (
    <div className="screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <div id="container">
          <div id="monitor">
            <div id="monitorscreen">
              <RoomDisplay sessions={props.sessions} />
            </div>
          </div>
        </div>
      </main>

      <footer>
        <Footer />
      </footer>
    </div>
  );
}

export const getStaticProps: GetStaticProps = async ({ preview = false }) => {
  const room = 'Room 1001';
  const { sessions } = await getSessions(preview, room);

  return {
    props: {
      sessions: sessions,
    },
    revalidate: 10,
  };
};
