import Head from 'next/head';
import { getBlogs } from '../api/queries/getBlogs';
import { GetStaticProps } from 'next';
import { Blog } from '../interfaces';
import RoomDisplay from '../components/RoomDisplay';
import Footer from '../components/Footer';

type RoomProps = {
  blogs: Blog[];
  preview: boolean;
};

export default function Room(props: RoomProps) {
  return (
    <div className="screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <div id="container">
          <div id="monitor">
            <div id="monitorscreen">
              <RoomDisplay blogs={props.blogs} />
            </div>
          </div>
        </div>
      </main>

      <footer>
        <Footer />
      </footer>
    </div>
  );
}

export const getStaticProps: GetStaticProps = async ({ preview = false }) => {
  const { blogs } = await getBlogs(preview);

  return {
    props: {
      blogs: blogs,
    },
    revalidate: 10,
  };
};
