import Head from 'next/head';
import Image from 'next/image';
import banner1 from '../public/banner1.png';
import Footer from '../components/Footer';

export default function Sponsor() {
  return (
    <div className="screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <div id="container">
          <div id="monitor">
            <div id="monitorscreen">
              {/* Added sponsor components here */}
              <Image src={banner1} alt="Sample" />
            </div>
          </div>
        </div>
      </main>

      <footer>
        <Footer />
      </footer>
    </div>
  );
}
