---
ID: "e7a0dba2-060b-53f3-81a3-3237baf30b86"
Parent: "3ee5e476-e843-51f1-a351-d2c3b198475a"
Template: "3ee5e476-e843-51f1-a351-d2c3b198475a"
Path: /sitecore/templates/Project/edgewebsite/HeroImage/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
