---
ID: "95418599-bea1-591e-a82e-99f2e978a58f"
Parent: "1f476f1c-822a-5a88-8f7e-2431b77d1b70"
Template: "1f476f1c-822a-5a88-8f7e-2431b77d1b70"
Path: /sitecore/templates/Project/edgewebsite/Section/__Standard Values
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "83d1ef67-13fb-4220-83ab-518113cb6fac"
