---
ID: "052c611f-c88c-5ebf-9afb-d7fbb61d0b35"
Parent: "11df8361-e7ca-5aa0-b224-7210c42f5fdd"
Template: "11df8361-e7ca-5aa0-b224-7210c42f5fdd"
Path: /sitecore/templates/Project/edgewebsite/ProductDetail/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210708T154804Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1eaf7a6b-3abb-43aa-9f7f-2de02f67f1ac"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210708T154804Z
