---
ID: "f8843bf7-a31a-4f71-8900-abd56b8fe34c"
Parent: "bbf6ffcd-cb4b-4363-a715-b2706e1b8ff9"
Template: "8ce42210-cad0-44f8-8ada-d88834a7ed2e"
Path: /sitecore/system/Modules/CMP/Config
SharedFields:
- ID: "21ca0142-2d9e-46ce-99e6-12adeebcd635"
  Hint: Default Language
  Value: en
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b3bc752f-65f8-4652-b0fb-92866add8b94"
