---
ID: "fe62fee2-98de-4ae4-b80f-f20f9f5e461a"
Parent: "905b44f3-db0d-4050-a738-1ece2ebb8509"
Template: "905b44f3-db0d-4050-a738-1ece2ebb8509"
Path: /sitecore/templates/Project/edgewebsite/CMP Entities/Testimony/__Standard Values
SharedFields:
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: 
- ID: "c9283d9e-7c29-4419-9c28-5a5c8ff53e84"
  Hint: __Bucketable
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "30de01d7-233e-42ac-bb14-751e9d60b1cd"
      Hint: Provider
      Value: $name
    - ID: "32fcc3c3-e6bb-4376-8bd8-bddb62fedb57"
      Hint: LogoTransformation
      Value: profile
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{C55B483C-EA7F-4E76-A066-985F7D9396CA}"
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f8cc29a4-3a41-4cc4-8737-e47d3adaadd7"
